# theme.toml template for a Hugo theme
description = "Roxo Hugo is a digital agency Hugo theme for creative agencies,  freelancers, graphic designers, photographers. Can be used for any kind of corporate websites who provides digital services with many expertise such as  Design, Digital Products, Development, Campaign & Content, Employer Branding, Animation & Motion Graphics ,Packaging & Product Design, Retail & Spacial, Print & Editorial Design, Concept/Text, Information Design etc. "
features = [
  'bootstrap 4',
  'responsive design',
  'blog',
  'responsive',
  'landing-page',
  'minimal',
  'business',
  'agency-template',
  'hugo-theme',
  'portfolio',
  'company',
  'creative',
  'contact-form',
]
homepage = "https://roxo-hugo.staticmania.com/"
license = "MIT"
licenselink = "https://github.com/StaticMania/roxo-hugo/blob/master/LICENSE"
min_version = "0.58.0"
name = "Roxo Hugo"
tags = [
  'clean',
  'minimal',
  'agency',
  'corporate',
  'creative agency',
  'creative studio',
  'portfolio',
  'staticmania',
  'responsive',
  'blog',
  'customizable',
  'company',
  'creative',
  'agency template',
]

[author]
homepage = "https://interetro.xyz/"
name = "Qiu Rui"

[original.author]
homepage = "https://staticmania.com/"
name = "Static Mania"
