baseURL = "http://example.org/"
languageCode = "en-us"
summarylength = 25
theme = "antidote"
title = "Antidote | a Hugo theme crafted by K2L"

# Site Menus
[menu]
# Navbar Menus
[[menu.nav]]
name = "Home"
url = ""
weight = 1
[[menu.nav]]
name = "About"
url = "about"
weight = 2
# [[menu.nav]]
# name = "Pricing"
# url = "price"
# weight = 3
[[menu.nav]]
name = "Portfolio"
url = "portfolio"
weight = 4
[[menu.nav]]
name = "Blog"
url = "blog"
weight = 5
[[menu.nav]]
name = "Let's talk!"
url = "contact"
weight = 6

# Site Params
[params]
dateFormat = "26 FEB 1994"
logo = "images/logo.png"
# Meta data
author = "Qiu Rui"
description = "Antidote | a Hugo theme crafted by K2L"
# Google Analitycs
googleAnalitycsID = "Your ID"
# We're using formspree.io for form handling, paste your formspree url below
formspreeFormUrl = "https://formspree.io/input_your_url_here"

# Navbar Action Button
[params.navAction]
name = "Get in touch"
status = true
url = "contact"

# Banner Section
[params.banner]
background_image = "images/backgrounds/hero-background.jpg"
enable = true
heading = "An Antidote to Chaos"
primary_button = "See our works"
primary_button_url = "portfolio"
secondary_button = "Connect with us"
secondary_button_url = "contact"
tagline = "12 RULES FOR LIFE"

[params.portfolio]
enable = true
subtitle = "Crafting experiences and seeking to make the complex clear & beautiful."
title = "OUR RECENT PROJECTS"

[params.call_to_action]
button = "Enquire"
button_url = "contact"
enable = true
title = "LET’S WORK TOGETHER"

[params.footer]
# Footer Contact Info
[params.footer.contactInfo]
address = "1 Elouera St.<br>Braddon, ACT 2612"
email = "info@k2l.com.au"
phone = "0422-222-222"
title = "Contact Info"
# Footer Sitemap
[params.footer.sitemap]
title = "Sitemap"
[[params.footer.sitemap.link]]
name = "About"
url = "about"
[[params.footer.sitemap.link]]
name = "Projects"
url = "portfolio"
[[params.footer.sitemap.link]]
name = "Blog"
url = "blog"
[[params.footer.sitemap.link]]
name = "Contact"
url = "contact"
# Footer Social Media
[params.footer.social]
title = "Social Media"
[[params.footer.social.link]]
name = "Medium"
url = "#"
[[params.footer.social.link]]
name = "Behance"
url = "#"
[[params.footer.social.link]]
name = "Dribbble"
url = "#"
[[params.footer.social.link]]
name = "Instagram"
url = "#"
# Footer Service
[params.footer.service]
description = "develop design solutions<br>produce valuable cultural content<br>create fresh brand experience"
title = "We help brands:"
